# Functions that should be executed before the build script is run
before_script: []

stages:
  - build
  - production

update_data:
  stage: build
  image: python:3.9
  script:
    - echo "Running test.py"
    - python test.py
    - echo "test.py run complete!"
    - git config --global user.email "ci-cd-bot@example.com"
    - git config --global user.name "CI/CD Bot""
    - git add new_file.txt # Add the file that was changed
    - git commit -m "new_file.txt created from pipeline"
    - git push origin HEAD:pipeline_testing # Replace 'master' with your branch name
  rules:
    - if: $TRIGGER_CONTEXT == "pipeline_test"
    
pages:
  stage: production
  image: busybox
  script:
    - echo "The site will be deployed to $CI_PAGES_URL"
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
