# Functions that should be executed before the build script is run
before_script: []

stages:
  - build
  - production

update_data:
  stage: build
  image: python:3.9
  script:
    - echo "Running update-data/main.py"
    - cd update-data
    - pip install -r /requirements.txt
    - python main.py
    - cd ..
    - echo "Running update-data/main.py complete!"
    - git config --global user.email "ci-cd-bot@example.com"
    - git config --global user.name "CI/CD Bot"
    - git remote set-url origin https://oauth2:${CI_ACCESS_TOKEN}@gitlab.fabcloud.org/pub/project/expert-network-map.git
    - git add . 
    - git commit -m "update-data/main.py ran"
    - git push origin HEAD:pipeline_testing 
  rules:
    - if: $TRIGGER_CONTEXT == "pipeline_test"
    
pages:
  stage: production
  image: busybox
  script:
    - echo "The site will be deployed to $CI_PAGES_URL"
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
