# Functions that should be executed before the build script is run
before_script: []

stages:
  - collect
  - format
  - production

update_data:
  stage: collect
  image: python:3.9
  script:
    - cd update-data
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - echo "Running update-data/main.py"
    - python main.py
    - cd ..
    - echo "Running update_data complete, now committing!"
    - git config --global user.email "ci-cd-bot@example.com"
    - git config --global user.name "CI/CD Bot"
    - git remote set-url origin https://oauth2:${CI_ACCESS_TOKEN}@gitlab.fabcloud.org/pub/project/expert-network-map.git
    - git add update-data/final_data.csv update-data/student_repo_id_saves/*.obj
    - git commit -m "update-data ran and final_data.csv updated"
    - git push origin HEAD:pipeline_testing
  timeout: 2 hours
  rules:
    - if: $TRIGGER_CONTEXT == "pipeline_test"
  tags:
    - longer

format_data:
  stage: format
  image: python:3.9
  script:
    - cd update-data
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - echo "Running update-data/matrix2d3js.py"
    - python matrix2d3js.py
    - echo "Running update-data/resolve_name_conflicts.py"
    - python resolve_name_conflicts.py
    - cat final_data_name_fixed.json > ./final_data.json
    - cd ..
    - echo "Running format_data complete, now committing!"
    - git config --global user.email "ci-cd-bot@example.com"
    - git config --global user.name "CI/CD Bot"
    - git remote set-url origin https://oauth2:${CI_ACCESS_TOKEN}@gitlab.fabcloud.org/pub/project/expert-network-map.git
    - mv update-data/final_data.json public/final_data.json
    - git add public/final_data.json
    - git diff --staged --exit-code || echo "Changes detected, proceeding with commit."
    - if [ $? -ne 0 ]; then git commit -m "format_data ran and final_data.json updated"; else echo "No changes to commit."; fi
    - git push origin HEAD:pipeline_testing
    - git fetch origin main
    - git stash
    - git switch main
    - git fetch origin pipeline_testing
    - git checkout pipeine_testing public/final_data.json
    - git commit -m "copied public/final_data.json from pipeline_testing branch after format_data ran"
    - git push origin HEAD:main
  timeout: 2 hours
  rules:
    - if: $TRIGGER_CONTEXT == "pipeline_test_2"
  tags:
    - longer 

pages:
  stage: production
  image: busybox
  script:
    - echo "The site will be deployed to $CI_PAGES_URL"
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
