# Functions that should be executed before the build script is run
before_script: []

update_data:
  image: python:3.9-slim-buster
  script:
    - echo "This is a test of the pipeline schedule"
  rules:
    - if: $TRIGGER_CONTEXT == "pipeline_test"
    
pages:
  image: busybox
  script:
    - echo "The site will be deployed to $CI_PAGES_URL"
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
